apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315069654700:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-s5iLLwbCscFS
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::471112969945:user/suresh
      username: suresh
    - groups:
      - expense-admin
      userarn: arn:aws:iam::471112969945:user/Ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-06T02:05:11Z"
  name: aws-auth
  namespace: kube-system
  uid: 63fbf183-6c54-4052-9d44-8d6644cfd97f



  #change arn 
  #take arn value from IAM after creating user  